-- Product candidates extracted from competitor / external pages
CREATE TABLE IF NOT EXISTS product_candidates (
  candidate_id CHAR(36) PRIMARY KEY,
  url TEXT NOT NULL,
  url_hash CHAR(64) NOT NULL,
  source_host VARCHAR(255) NOT NULL,
  content_hash CHAR(64) NOT NULL,
  structure_hash CHAR(64) NOT NULL,
  product_title VARCHAR(255) NULL,
  brand VARCHAR(160) NULL,
  variant VARCHAR(255) NULL,
  nicotine_mg DECIMAL(6,2) NULL,
  volume_ml DECIMAL(8,2) NULL,
  pack_count INT NULL,
  price_detected DECIMAL(10,2) NULL,
  currency CHAR(8) NULL,
  json_ld_json JSON NULL,
  microdata_json JSON NULL,
  og_json JSON NULL,
  heuristic_json JSON NULL,
  extracted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  first_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  change_count INT NOT NULL DEFAULT 0,
  status ENUM('active','superseded') NOT NULL DEFAULT 'active',
  UNIQUE KEY uq_candidate_identity (url_hash, content_hash),
  KEY idx_host (source_host),
  KEY idx_brand_variant (brand, variant),
  KEY idx_title (product_title(100))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;