<?php /** @var array $patches */ ?>
<div class="container mt-4 autotune-approval">
  <h1 class="h3 mb-3">Auto-Tune Threshold Suggestions</h1>
  <p class="text-muted">These SQL patch files were generated automatically from drift + calibration analytics. Review carefully before applying. Application executes statements in a single transaction.</p>
  <?php if(isset($_GET['applied'])): ?>
    <div class="alert alert-success py-2">Patch applied successfully.</div>
  <?php endif; ?>
  <?php if(empty($patches)): ?>
    <div class="alert alert-info py-2">No pending patch files found.</div>
  <?php else: ?>
    <div class="row g-3">
      <?php foreach($patches as $p): ?>
        <div class="col-md-6">
          <div class="card shadow-sm h-100">
            <div class="card-header d-flex justify-content-between align-items-center">
              <span class="fw-semibold"><i class="fa fa-database me-1"></i><?= htmlspecialchars($p['file']) ?></span>
              <small class="text-muted"><?= htmlspecialchars($p['mtime']) ?></small>
            </div>
            <div class="card-body">
              <div class="small text-muted mb-2">Size: <?= number_format($p['size']) ?> bytes</div>
              <pre class="bg-light p-2 border rounded small mb-3" style="max-height:220px;overflow:auto;white-space:pre;"><code><?= $p['preview'] ?></code></pre>
              <form method="post" action="/autotune/apply" onsubmit="return confirm('Apply patch <?= htmlspecialchars($p['file']) ?>? This will modify thresholds.');">
                <input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrf_token) ?>">
                <input type="hidden" name="file" value="<?= htmlspecialchars($p['file']) ?>">
                <button class="btn btn-sm btn-primary"><i class="fa fa-check me-1"></i>Apply Patch</button>
                <a href="/download/tmp/<?= urlencode($p['file']) ?>" class="btn btn-sm btn-outline-secondary">Download</a>
              </form>
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <hr class="my-4"/>
  <h2 class="h5">Operational Guidance</h2>
  <ul class="small">
    <li>Only apply one patch at a time and observe acceptance precision post-change.</li>
    <li>Rollback by manually editing affected rows in <code>product_match_thresholds</code> (future: automated rollback).</li>
    <li>Patches are generated by <code>bin/auto_tune_patch_generator.php</code>.</li>
  </ul>
</div>
